# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Administrator\Desktop\界面优化2\main.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1367, 770)
        MainWindow.setMinimumSize(QtCore.QSize(1367, 770))
        MainWindow.setMaximumSize(QtCore.QSize(1367, 770))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1367, 71))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.huanyin = QtWidgets.QLabel(self.frame)
        self.huanyin.setGeometry(QtCore.QRect(40, 20, 231, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.huanyin.setFont(font)
        self.huanyin.setObjectName("huanyin")
        self.tubiao = QtWidgets.QLabel(self.frame)
        self.tubiao.setGeometry(QtCore.QRect(1050, 19, 29, 42))
        self.tubiao.setText("")
        self.tubiao.setObjectName("tubiao")
        self.userimg = QtWidgets.QLabel(self.frame)
        self.userimg.setGeometry(QtCore.QRect(1089, 15, 44, 46))
        self.userimg.setText("")
        self.userimg.setObjectName("userimg")
        self.username = QtWidgets.QLabel(self.frame)
        self.username.setGeometry(QtCore.QRect(1155, 19, 131, 24))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.username.setFont(font)
        self.username.setObjectName("username")

        self.time = QtWidgets.QLabel(self.frame)
        self.time.setText("")
        self.time.setObjectName("time")
        self.time.setFont(font)
        self.time.setFixedWidth(250)
        self.time.setFixedHeight(20)
        self.time.setGeometry(QtCore.QRect(600, 26, 131, 46))




        self.frame_3 = QtWidgets.QFrame(self.centralWidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 71, 1371, 701))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.textEdit = QtWidgets.QTextEdit(self.frame_3)
        self.textEdit.setGeometry(QtCore.QRect(350, 590, 906, 81))
        self.textEdit.setStyleSheet("font: 14pt \"微软雅黑\";")
        self.textEdit.setObjectName("textEdit")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 71, 701))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 80, 51, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setGeometry(QtCore.QRect(80, 30, 278, 641))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setGeometry(QtCore.QRect(110, 130, 54, 12))
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_4)#群聊
        self.pushButton_3.setGeometry(QtCore.QRect(50, 40, 181, 71))
        self.pushButton_3.setObjectName("pushButton_3")
        self.listWidget = QtWidgets.QListWidget(self.frame_4)
        self.listWidget.setGeometry(QtCore.QRect(20, 160, 241, 301))
        self.listWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget.setObjectName("listWidget")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setGeometry(QtCore.QRect(390, 30, 906, 481))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_5)
        self.textBrowser.setGeometry(QtCore.QRect(0, 100, 911, 381))
        self.textBrowser.setObjectName("textBrowser")
        self.closebutton = QtWidgets.QPushButton(self.frame)
        self.closebutton.setGeometry(QtCore.QRect(1340, 0, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.closebutton.setFont(font)
        self.closebutton.setObjectName("closebutton")
        self.minbutton = QtWidgets.QPushButton(self.frame)
        self.minbutton.setGeometry(QtCore.QRect(1310, 0, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.minbutton.setFont(font)
        self.minbutton.setObjectName("minbutton")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setGeometry(QtCore.QRect(410, 60, 131, 31))
        font = QtGui.QFont()
        font.setFamily("华文彩云")
        font.setPointSize(18)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_5.setGeometry(QtCore.QRect(854, 0, 51, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_5)
        self.tableWidget.setGeometry(QtCore.QRect(390, 270, 301, 181))
        self.tableWidget.setRowCount(6)
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_4.setGeometry(QtCore.QRect(1150, 610, 51, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setGeometry(QtCore.QRect(349, 529, 901, 51))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")

        self.pushButton_6 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_6.setGeometry(QtCore.QRect(500, 10, 40, 40))
        self.pushButton_6.setObjectName("pushButton_6")

        self.SizeComboBox = QtWidgets.QComboBox(self.frame_6)
        self.SizeComboBox.setGeometry(QtCore.QRect(250, 20, 69, 22))
        self.SizeComboBox.setObjectName("SizeComboBox")
        self.SizeComboBox.addItem("")
        self.SizeComboBox.addItem("")
        self.SizeComboBox.addItem("")
        self.SizeComboBox.addItem("")
        self.SizeComboBox.addItem("")
        self.SizeComboBox.addItem("")
        self.SizeComboBox.addItem("")
        self.SizeComboBox.addItem("")
        self.SizeComboBox.addItem("")
        self.SizeComboBox.addItem("")
        self.SizeComboBox.addItem("")
        self.SizeComboBox.addItem("")
        self.SizeComboBox.addItem("")
        self.SizeComboBox.addItem("")
        self.SizeComboBox.addItem("")

        #文件发送按钮
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_7.setGeometry(QtCore.QRect(560, 10, 40, 40))
        self.pushButton_7.setObjectName("pushButton_7")

        self.colorToolBtn = QtWidgets.QToolButton(self.frame_6)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./images/color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.colorToolBtn.setIcon(icon3)
        self.colorToolBtn.setIconSize(QtCore.QSize(42, 42))
        # self.colorToolBtn.setAutoRaise(True)
        # self.colorToolBtn.setEditable(False)
        self.colorToolBtn.setGeometry(QtCore.QRect(440, 10, 40, 40))
        self.colorToolBtn.setObjectName("colorToolBtn")

        self.fontComboBox = QtWidgets.QFontComboBox(self.frame_6)
        self.fontComboBox.setGeometry(QtCore.QRect(50, 20, 189, 22))
        self.fontComboBox.setEditable(False)
        self.fontComboBox.setObjectName("fontComboBox")

        self.pushButton_6.raise_()
        self.SizeComboBox.raise_()
        self.fontComboBox.raise_()
        self.pushButton_7.raise_()

        self.frame_5.raise_()
        self.frame_4.raise_()
        self.textEdit.raise_()
        self.pushButton_4.raise_()
        self.frame_6.raise_()

        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.minbutton.clicked.connect(MainWindow.lower)
        self.closebutton.clicked.connect(MainWindow.close)
        # self.fontComboBox.currentIndexChanged['QString'].connect(self.textEdit.setFontFamily)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.huanyin.setText(_translate("MainWindow", "欢迎进入聊天室"))
        self.username.setText(_translate("MainWindow", "测试人员"))
        self.closebutton.setText(_translate("MainWindow", "X"))
        self.minbutton.setText(_translate("MainWindow", "-"))
        # self.pushButton.setText(_translate("MainWindow", "天气"))
        #self.pushButton_2.setText(_translate("MainWindow", ""))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))

        self.textBrowser.setHtml(_translate("MainWindow",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))

        self.label.setText(_translate("MainWindow", "我的好友"))
        self.pushButton_3.setText(_translate("MainWindow", "群聊天室"))
        self.label_2.setText(_translate("MainWindow", "1806聊天室"))
        # self.pushButton_5.setText(_translate("MainWindow", "关闭"))
        # self.pushButton_4.setText(_translate("MainWindow", "发送"))
        # self.pushButton_6.setText(_translate("MainWindow", "表情"))
        self.SizeComboBox.setItemText(0, _translate("MainWindow", "9"))
        self.SizeComboBox.setItemText(1, _translate("MainWindow", "10"))
        self.SizeComboBox.setItemText(2, _translate("MainWindow", "11"))
        self.SizeComboBox.setItemText(3, _translate("MainWindow", "12"))
        self.SizeComboBox.setItemText(4, _translate("MainWindow", "13"))
        self.SizeComboBox.setItemText(5, _translate("MainWindow", "14"))
        self.SizeComboBox.setItemText(6, _translate("MainWindow", "15"))
        self.SizeComboBox.setItemText(7, _translate("MainWindow", "16"))
        self.SizeComboBox.setItemText(8, _translate("MainWindow", "17"))
        self.SizeComboBox.setItemText(9, _translate("MainWindow", "18"))
        self.SizeComboBox.setItemText(10, _translate("MainWindow", "19"))
        self.SizeComboBox.setItemText(11, _translate("MainWindow", "20"))
        self.SizeComboBox.setItemText(12, _translate("MainWindow", "21"))
        self.SizeComboBox.setItemText(13, _translate("MainWindow", "22"))
        self.SizeComboBox.setItemText(14, _translate("MainWindow", "23"))
        # self.pushButton_7.setText(_translate("MainWindow", "文件"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())

