# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyWeather.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(422, 691)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        Form.setFont(font)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 20, 381, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 60, 131, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(150, 60, 71, 31))
        self.pushButton.setObjectName("pushButton")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(230, 60, 121, 31))
        self.checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox.setObjectName("checkBox")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(10, 100, 401, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(0, 0, 549, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(Form)
        self.line_5.setGeometry(QtCore.QRect(10, 220, 401, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(10, 240, 401, 441))
        self.textEdit.setObjectName("textEdit")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 110, 401, 26))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.CitypushButton01 = QtWidgets.QPushButton(self.widget)
        self.CitypushButton01.setObjectName("CitypushButton01")
        self.horizontalLayout_3.addWidget(self.CitypushButton01)
        self.CitypushButton02 = QtWidgets.QPushButton(self.widget)
        self.CitypushButton02.setObjectName("CitypushButton02")
        self.horizontalLayout_3.addWidget(self.CitypushButton02)
        self.CitypushButton03 = QtWidgets.QPushButton(self.widget)
        self.CitypushButton03.setObjectName("CitypushButton03")
        self.horizontalLayout_3.addWidget(self.CitypushButton03)
        self.CitypushButton04 = QtWidgets.QPushButton(self.widget)
        self.CitypushButton04.setObjectName("CitypushButton04")
        self.horizontalLayout_3.addWidget(self.CitypushButton04)
        self.CitypushButton05 = QtWidgets.QPushButton(self.widget)
        self.CitypushButton05.setObjectName("CitypushButton05")
        self.horizontalLayout_3.addWidget(self.CitypushButton05)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(10, 140, 401, 26))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.CitypushButton06 = QtWidgets.QPushButton(self.widget1)
        self.CitypushButton06.setObjectName("CitypushButton06")
        self.horizontalLayout_4.addWidget(self.CitypushButton06)
        self.CitypushButton07 = QtWidgets.QPushButton(self.widget1)
        self.CitypushButton07.setObjectName("CitypushButton07")
        self.horizontalLayout_4.addWidget(self.CitypushButton07)
        self.CitypushButton08 = QtWidgets.QPushButton(self.widget1)
        self.CitypushButton08.setObjectName("CitypushButton08")
        self.horizontalLayout_4.addWidget(self.CitypushButton08)
        self.CitypushButton09 = QtWidgets.QPushButton(self.widget1)
        self.CitypushButton09.setObjectName("CitypushButton09")
        self.horizontalLayout_4.addWidget(self.CitypushButton09)
        self.CitypushButton10 = QtWidgets.QPushButton(self.widget1)
        self.CitypushButton10.setObjectName("CitypushButton10")
        self.horizontalLayout_4.addWidget(self.CitypushButton10)
        self.widget2 = QtWidgets.QWidget(Form)
        self.widget2.setGeometry(QtCore.QRect(10, 170, 401, 26))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.CitypushButton11 = QtWidgets.QPushButton(self.widget2)
        self.CitypushButton11.setObjectName("CitypushButton11")
        self.horizontalLayout_5.addWidget(self.CitypushButton11)
        self.CitypushButton12 = QtWidgets.QPushButton(self.widget2)
        self.CitypushButton12.setObjectName("CitypushButton12")
        self.horizontalLayout_5.addWidget(self.CitypushButton12)
        self.CitypushButton13 = QtWidgets.QPushButton(self.widget2)
        self.CitypushButton13.setObjectName("CitypushButton13")
        self.horizontalLayout_5.addWidget(self.CitypushButton13)
        self.CitypushButton14 = QtWidgets.QPushButton(self.widget2)
        self.CitypushButton14.setObjectName("CitypushButton14")
        self.horizontalLayout_5.addWidget(self.CitypushButton14)
        self.CitypushButton15 = QtWidgets.QPushButton(self.widget2)
        self.CitypushButton15.setObjectName("CitypushButton15")
        self.horizontalLayout_5.addWidget(self.CitypushButton15)
        self.widget3 = QtWidgets.QWidget(Form)
        self.widget3.setGeometry(QtCore.QRect(10, 200, 401, 26))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.CitypushButton16 = QtWidgets.QPushButton(self.widget3)
        self.CitypushButton16.setObjectName("CitypushButton16")
        self.horizontalLayout_6.addWidget(self.CitypushButton16)
        self.CitypushButton17 = QtWidgets.QPushButton(self.widget3)
        self.CitypushButton17.setObjectName("CitypushButton17")
        self.horizontalLayout_6.addWidget(self.CitypushButton17)
        self.CitypushButton18 = QtWidgets.QPushButton(self.widget3)
        self.CitypushButton18.setObjectName("CitypushButton18")
        self.horizontalLayout_6.addWidget(self.CitypushButton18)
        self.CitypushButton19 = QtWidgets.QPushButton(self.widget3)
        self.CitypushButton19.setObjectName("CitypushButton19")
        self.horizontalLayout_6.addWidget(self.CitypushButton19)
        self.CitypushButton20 = QtWidgets.QPushButton(self.widget3)
        self.CitypushButton20.setObjectName("CitypushButton20")
        self.horizontalLayout_6.addWidget(self.CitypushButton20)

        self.retranslateUi(Form)

        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Wetach Forecast"))
        self.label.setText(_translate("Form", "请输入城市名称或点击热门城市："))
        self.pushButton.setText(_translate("Form", "查询"))
        self.checkBox.setText(_translate("Form", "未来四天天气"))
        self.CitypushButton01.setText(_translate("Form", "北京"))
        self.CitypushButton02.setText(_translate("Form", "上海"))
        self.CitypushButton03.setText(_translate("Form", "广州"))
        self.CitypushButton04.setText(_translate("Form", "南京"))
        self.CitypushButton05.setText(_translate("Form", "西安"))
        self.CitypushButton06.setText(_translate("Form", "成都"))
        self.CitypushButton07.setText(_translate("Form", "武汉"))
        self.CitypushButton08.setText(_translate("Form", "合肥"))
        self.CitypushButton09.setText(_translate("Form", "石家庄"))
        self.CitypushButton10.setText(_translate("Form", "天津"))
        self.CitypushButton11.setText(_translate("Form", "郑州"))
        self.CitypushButton12.setText(_translate("Form", "重庆"))
        self.CitypushButton13.setText(_translate("Form", "乌鲁木齐"))
        self.CitypushButton14.setText(_translate("Form", "深圳"))
        self.CitypushButton15.setText(_translate("Form", "洛阳"))
        self.CitypushButton16.setText(_translate("Form", "济南"))
        self.CitypushButton17.setText(_translate("Form", "杭州"))
        self.CitypushButton18.setText(_translate("Form", "长沙"))
        self.CitypushButton19.setText(_translate("Form", "哈尔滨"))
        self.CitypushButton20.setText(_translate("Form", "沈阳"))

